### PR TITLE
closes #11, #5 Fixes issues with LOCALE

### LINKED ISSUE #11: Different load metrics, depending on the OS version (debian in my case)
Hello,

The load metrics are different depending on the uptime command output.
Examples :

vm 1 (0<metrics<1)
# uptime

 18:49:03 up 116 days, 21 min,  2 users,  load average: 0.86, 1.15, 1.04
# /opt/sensu/embedded/bin/metrics-load.rb -p

maamsprd01.amabis.ma.load_avg.one 0.22 1475858943
maamsprd01.amabis.ma.load_avg.five 0.29 1475858943
maamsprd01.amabis.ma.load_avg.fifteen 0.26 1475858943

vm2 (0<metrics<100   %)
# uptime

  17:48:54 up 105 days,  6:00,  0 users,  load average: 0,82, 0,96, 0,77
# /opt/sensu/embedded/bin/metrics-load.rb -p

masmtprd01.amabis.ma.load_avg.one 41.0 1475858935
masmtprd01.amabis.ma.load_avg.five 48.0 1475858935
masmtprd01.amabis.ma.load_avg.fifteen 38.5 1475858935

Maybe the line https://github.com/sensu-plugins/sensu-plugins-load-checks/blob/master/bin/metrics-load.rb#L61 must be update to include floats with '.' ;

### PR DESCRIPTION
**Pull request by majormoses**
Breaking Change Release:
- Removed per-core option as the defaults changed and honestly I don't think they ever made sense. Without knowing the number of cores load averages are a useless metric to monitor.

Non Breaking Changes:
- moved common logic our of check-load.rb
- metrics-load.rb now use common logic
- fixed common logic for LOCALE

#### General

- [x] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [x] Update README with any necessary configuration snippets

- [x] Binstubs are created if needed

- [x] RuboCop passes

- [x] Existing tests pass 

#### Purpose
Fix locale parsing issues. As part of this I moved the location of shared logic into a more sensible location.
#### Known Compatibility Issues
Option per_core is no longer used. This is a breaking change.

### CODE REVIEW

**Comment by eheydrick** [comment]
I'll give this a shot on my systems tomorrow.

File: bin/check-load.rb [hunk 1]
```diff
@@ -81,25 +41,14 @@ class CheckLoad < Sensu::Plugin::Check::CLI
...
-         short: '-p',
-         long: '--per-core',
-         description: 'Divide load average results by cpu/core count',
-         boolean: 'true',
-         default: true
-
   def run
-    avg = LoadAverage.new(config[:per_core])
-    unknown 'Could not read load average from /proc' if avg.failed?
+    data = LoadAverage.new(config[:per_core])
```
Comment (eheydrick) [inline bin/check-load.rb]: Why pass `config[:per_core]` if that option is removed?

File: bin/metrics-load.rb [hunk 2]
```diff
@@ -46,40 +47,25 @@ class LoadStat < Sensu::Plugin::Metric::CLI::Graphite
...
-                 File.read('/proc/cpuinfo').scan(/^processor/).count
-               else
-                 `sysctl -n hw.ncpu`.to_i
-               end
-  end
-
   def run
-    result = `uptime`.delete(',').split(' ')
-    result = result[-3..-1]
+    data = LoadAverage.new(config[:per_core])
```
Comment (eheydrick) [inline bin/metrics-load.rb]: Ditto on `config[:per_core]`

**Review by eheydrick — COMMENTED** [review]
I get the same load avg for "per-core" and "total" load and it's the actual load on this 4 core system. We're only doing per-core load now, correct?

File: bin/check-load.rb (hunk 1 above)
Comment (majormoses) [reply bin/check-load.rb]: Sorry I missed that.

**Comment by majormoses** [comment]
Sorry about that I totally broke something but its fixed now:

cores:
```
$ nproc 
8
```
load:
```
$ uptime
 17:53:48 up 1 day,  6:00,  8 users,  load average: 0.24, 0.34, 0.42
```
metrics-load.rb:
```
$ ./bin/metrics-load.rb 
babrams-Serval-WS.load_avg.one 0.03 1495068815
babrams-Serval-WS.load_avg.five 0.04 1495068815
babrams-Serval-WS.load_avg.fifteen 0.05 1495068815
```
check-load.rb:
```
$ ./bin/check-load.rb
CheckLoad OK: Per core load average (8 CPU): [0.03, 0.04, 0.05]
```

**Comment by majormoses** [comment]
@eheydrick fixed up those issues, last push was just removing some commented out debug statements I forgot to cleanup.

**Review by eheydrick — APPROVED** [review]

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-load-checks/versions/3.0.0

**Comment by rs-mrichmond** [comment]
ugh. Why couldn't you just leave the stub the '-p' flag in place.

Going to per-core as default makes sense, but leaving the flag stub would have meant those already using per-core wouldn't have to change anything.

:(

**Comment by majormoses** [comment]
@rs-mrichmond yes I debated this a lot internally and decided we should make the next major version make sense (we already tried to transition this behavior in the last major) as there has been a lot of confusion on this and I wanted to make the experience good for new users and allow existing users to change their config without breaking before using the new gem. We had to deprecate it at some point as I don't like leaving useless features that people will open issues on it not doing what they expect when they try to change the behavior that no longer did anything. Doing this in 2 major releases (1 to change the behavior and another to remove the old behavior completely) seemed reasonable to me given the minimal effort to upgrade this. The only reason I can see this being a big effort to upgrade is if you are not using Config Management, is there something else I am not accounting for that makes this hard?

**Comment by majormoses** [comment]
@rs-mrichmond on the general topic on breaking changes I tend to hold the belief that when they can be avoided they should.
Here are some caveats I used to justify this change:
- quality of code (I discovered that even when using `--per-core=false` passed in it did not do what was intended and rather than waste time doing something hacky I decided to just bite the bullet and do it right)
- poor user experience

This still requires them to be documented as a breaking change and a major version bump. I always call out these changes in CHANGELOG under a `## Breaking Changes` section so I am not sure what else we can do to make this obvious to the user. I also believe that breaking changes should never be self merged (had proper review here) to discuss and justify the changes. I am certainly open to suggestions on how I can improve this.

**Comment by rs-mrichmond** [comment]
The only thing I would have done differently is make the check kick an unknown error code (not 0,1,2) for a version with a deprecation warning for version 2.0.0

I currently do config management but not really effective management of sensu plugins. I haven't really seen a good/effective way to handle updating all installed plugins.

I wasn't expecting this change and when spinning up a production node during a once-a-week maintenance window the check was failing. So now I have a one week period without a working load average check on that server. :(

**Comment by majormoses** [comment]
@rs-mrichmond that's a great suggestion regarding using unknown for the intermediate release I will do that in the future if a situation ever arises. I use chef to manage all aspects of sensu setup which includes version pinning the plugins/gems installed into sensu embedded ruby. If you hit me up via IRC I am more than happy to share how I do this.

> I wasn't expecting this change and when spinning up a production node during a once-a-week maintenance window

This is why pinning (especially at least to a major) versions are important. Pinning and reading the CHANGELOG when bumping a new major version would have prevented this.

**Comment by egarbi** [comment]
today I rebuilt a couple of clients to realise that check-load is failing on those because the '-p' option isn't available anymore, so I will need to put some weird logic in place to skip '-p' based on the version of check or something like that. not cool :)

**Comment by egarbi** [comment]
well, no so bad, I finally ended up upgrading the check everywhere. Thanks
